// File generated by Antigravity to support Web/Chrome and Android Firebase config.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd3g69wYo_jWVfqql_4yF16ev_OBKCNRs',
    appId: '1:283136281850:web:YOUR_WEB_APP_ID_HERE', // User needs to replace this with their Firebase Web App ID
    messagingSenderId: '283136281850',
    projectId: 'women-safety-app-b8600',
    authDomain: 'women-safety-app-b8600.firebaseapp.com',
    storageBucket: 'women-safety-app-b8600.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd3g69wYo_jWVfqql_4yF16ev_OBKCNRs',
    appId: '1:283136281850:android:22bb4d16f6cffe4e9c0d43',
    messagingSenderId: '283136281850',
    projectId: 'women-safety-app-b8600',
    storageBucket: 'women-safety-app-b8600.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd3g69wYo_jWVfqql_4yF16ev_OBKCNRs',
    appId: '1:283136281850:ios:YOUR_IOS_APP_ID_HERE',
    messagingSenderId: '283136281850',
    projectId: 'women-safety-app-b8600',
    storageBucket: 'women-safety-app-b8600.firebasestorage.app',
    iosBundleId: 'com.example.hutter',
  );
}
